# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      makelib.py
#       Purpose :   Create the library file
#       Date :      11th March 2025
#       Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,re

include = []
assembler = []
for root,dirs,files in os.walk("../assembler"):
    for f in files:
        if f.endswith(".asm"):
            assembler.append(root+os.sep+f)
        if f.endswith(".inc"):
            include.append(root+os.sep+f)

assembler.sort()
include.sort()

print(";\n;\tThis file is automatically generated.\n;")
for f in include+assembler:
    for s in open(f).readlines():
        print(s.rstrip())
    