# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      makefarcall.py
#       Purpose :   Create the far call code.
#       Date :      11th March 2025
#       Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,re

routines = {}

for root,dirs,files in os.walk(sys.argv[1]):
    for f in [x for x in files if x.endswith(".asm") and not x.startswith("__")]:
        for s in open(root + os.sep + f).readlines():
            if s.find("farjsr") >= 0:
                m = re.match("^\\s*farjsr\\s*([0-9A-F]+)",s)
                if m is not None:
                    routines[m.group(1)] = m.group(1)

routineList = [x for x in routines.keys()]                    

print(";\n;\tThis file is automatically generated.\n;")
for r in routineList:
    print("TA_Call_{0}:".format(r))
    print("\tjsr\t$FF6E")                                       # jsrfar
    print("\t.word\t${0}".format(r))                            # address
    print("\t.byte\t0")                                         # ROM page 0 is the Kernal.
    print("\trts\n")
