# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		Makefile
#		Purpose :	Test the assembler actually works , not main unit tests.
#		Date :		11th March 2025
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

include ../build_env/common.make
#
#		This is just a test build. Use make asm / make run / make runexit to actually do stuff.
#
build:
	$(MAKE)-B asm
	echo "Assembled successfully."